#!/bin/sh
### BEGIN INIT INFO
# Provides:          timeboxd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


case "$1" in
  start)
    echo "Starting example"
    # run application you want to start
    /home/pi/wiegand/timebox.py &
    ;;
  stop)
    echo "Stopping example"
    # kill application you want to stop
    pkill timebox.py
    ;;
  *)
    echo "Usage: /etc/init.d/example{start|stop}"
    exit 1
    ;;
esac
 
exit 0


